### PR TITLE
Add option to disable room topic echos from Matrix

### PR DESCRIPTION
**Pull request by Miepee**
This PR adds another config value, in order to disable forwarding room topic echos on Matrix to Discord.

### CODE REVIEW

**Review by Half-Shot — CHANGES_REQUESTED** [review]
Changes look good, but can you add a test next to https://github.com/matrix-org/matrix-appservice-discord/blob/develop/test/test_matrixeventprocessor.ts#L345-L356? I think all you need to do is modify the createMatrixEventProcessor function to take a parameter which customises the config, and then test for no topic notifs.

Thanks!

**Comment by Miepee** [comment]
I originally didn't add a test case, because the join/leave and invite echos don't have a test case either for not sending a message when the config has it disabled.
Should I add the test cases for those too then?

**Comment by Half-Shot** [comment]
> I originally didn't add a test case, because the join/leave and invite echos don't have a test case either for not sending a message when the config has it disabled. Should I add the test cases for those too then?

That's definitely an oversight. Extra points if you do those too, but I'm also happy just to accept changes for the things you tested.

**Review by Half-Shot — APPROVED** [review]
Looks good to me!

**Pull request merged**
