### PR TITLE
Added "Reactions" to the features/roadmap list

### PR DESCRIPTION
**Pull request by MightyCreak**

### CODE REVIEW

**Review by JulianGro — APPROVED** [review]

**Review by kevincox — APPROVED** [review]

**Comment by MightyCreak** [comment]
This PR is pretty simple and harmless, what should I do for it to be merged into `develop`? Thx

**Comment by Jaykul** [comment]
Makes sense to merge

**Comment by MightyCreak** [comment]
Why my PR has been closed? Has reactions been fixed?

**Comment by MightyCreak** [comment]
Ah ok... I think it's been closed because I deleted my forked repo. So I created a new one and redid the PR: #784

**Pull request closed without merging**
