### PR TITLE
Track a slightly fresher fork of better-discord.js

### PR DESCRIPTION
**Pull request by tadzik**
This fixes a crash related to voice channel message handling.

### CODE REVIEW

**Review by Half-Shot — APPROVED** [review]
Seems good, changelog please :)

**Comment by FSG-Cat** [comment]
If I may ask why are we switching to a branch that is a a single commit ahead? Isn't it a better idea to then climb up the tree to discordjs main if we want a more updated version?

**Comment by Half-Shot** [comment]
Hiya @FSG-Cat, it's a good point:

We're updating to fix a specific bug, and are considering updating to stock in the future. It would take considerable effort to refactor the bridge for the moment, so we want to ensure we fix the more pressing bug, then circle back to refactoring later :)

Thanks for raising it!

**Comment by Miepee** [comment]
Which bug was it? If it's user facing, maybe mention that in the changelog as well?

**Comment by FSG-Cat** [comment]
> Hiya @FSG-Cat, it's a good point:
> 
> We're updating to fix a specific bug, and are considering updating to stock in the future. It would take considerable effort to refactor the bridge for the moment, so we want to ensure we fix the more pressing bug, then circle back to refactoring later :)
> 
> Thanks for raising it!

Thanks for the information.

**Comment by turt2live** [comment]
uh, you should be able to switch to upstream.

**Comment by erkinalp** [comment]
alternative: switch to fosscord.js which is a fork of discord.js with third party instance support.

**Comment by tadzik** [comment]
I clarified the issue in both the commit message and the changelog.

The switch to upstream discord/fosscord.js is very much on our radar, but given how far behind we are and all the API changes that happened in the upstream since the version we're on, this is a significantly bigger effort that'll take us a while to complete.

This is a hotfix to fix a voice-channel related crash, just to improve the stability of the bridge while the proper upstream sync is still brewing.

**Pull request merged**
