### PR TITLE
use correct name when mentioning

### PR DESCRIPTION
**Pull request by Sorunome**
Problem: When mentioning a user on discord who has a nickname set the created pill on the riot side contained their username, not their nickname

This problem wasn't visible in desktop riot due to desktop riot ignoring what the actual contents were, however, it is very visible on android riot

### CODE REVIEW

**Comment by Half-Shot** [comment]
Works for me. Do we test this?

**Comment by Sorunome** [comment]
What do you mean? It fixes the issue i outlined in the top post, you can notice the issue if you hit "View Source" on the matrix message.

riot-web does some extra parsing on user pills so riot-desktop didn't show that bug, but riot-android did. And possibly other clients.

**Comment by Sorunome** [comment]
oh, you meant automated test thingies, added that now

**Comment by Sorunome** [comment]
I guess me just derped, hang on

**Pull request merged**
