### PR TITLE
Port to ESLint (continuation)

### PR DESCRIPTION
**Pull request by jaller94**
Continuation of #605.

### CODE REVIEW

**Review by Half-Shot — APPROVED** [review]
Looks fine, suggest you fix the merge conflict :)

**Comment by jaller94** [comment]
@Half-Shot I resolved the merge conflicts.

**Comment by Sorunome** [comment]
@jaller94 there are MCs again ^^"

**Comment by jaller94** [comment]
I resolved the merge conflicts.

**Pull request merged**
