### PR TITLE
Replace npmlog with winston

### PR DESCRIPTION
**Pull request by Half-Shot**

### CODE REVIEW

**Comment by Half-Shot** [comment]
I think this PR is ready, pending review from interested parties.

But I'm holding off until we have the major PRs merged because of the conflicts.

**Comment by turt2live** [comment]
I would have settled for timestamps, but this is much more interesting :D

It would be nice to be able to disable file logging entirely and instead opt for console logging. This is in particularly useful for Docker containers which don't need the logs duplicated.

**Comment by Half-Shot** [comment]
>It would be nice to be able to disable file logging entirely and instead opt for console logging. This is in particularly useful for Docker containers which don't need the logs duplicated.

It does that by default?

**Comment by Half-Shot** [comment]
Yaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaymergeddddd

**Pull request merged**
