### PR TITLE
Webhook description isn't allowed (apparently)

### PR DESCRIPTION
**Pull request by turt2live**
I'm 99% sure this isn't the correct fix, but the project doesn't build without it for me.

### CODE REVIEW

**Comment by Half-Shot** [comment]
Not so fast? I seem to be able to build it okay. Do we have some mismatch somewhere?

**Comment by turt2live** [comment]
Probably. I can't get around the error with discordjs 11.1.0 on any platform.

**Comment by turt2live** [comment]
A version mismatch between our environments seems to have caused this problem.

**Comment by Half-Shot** [comment]
Yeah, looks like we do require it on develop. Sorry.

**Pull request closed without merging**
