### PR TITLE
Channel stuff

### LINKED ISSUE #69: Deleted channels are handled awkwardly
There should be some kind of indication when a channel is deleted, because in their current state, deleted channels do not show any sign of deletion, and can cause confusion.<br><br>Some of the following should be done to reduce confusion:<br><ul><li>Changing name/topic</li><li>Setting message sending power level to 100</li><li>Room directory delisting[Current homeserver only, obviously]</li><li>Unsetting appservice room alias</li><li>Setting invite only mode.</li><li>Parting all appservice ghosts</li><li>Stop bridging join/parts&avatar/nick changes</li></ul><br>

### PR DESCRIPTION
**Pull request by Sorunome**
This PR is a continuing of #125 

Thus, fixes #69 

Somehow alias isn't removed, however the canonical alias is removed if it is the discord one

still needs tests

### CODE REVIEW

**Comment by Sorunome** [comment]
I'm not quite sure how to write tests for this, help would be welcome

**Comment by Sorunome** [comment]
Having made this a more general synchronizer, i started moving some other stuff there and, in the process, also tackled #191 and #7

**Comment by Half-Shot** [comment]
Thanks a ton for this, it's on the review radar, I just need time to read it though :)

**Comment by Half-Shot** [comment]
This has been superseded by #252

**Pull request closed without merging**
