### PR TITLE
Remove edit link embed

### LINKED ISSUE #641: After editing on Matrix, the posted edit message on Discord has an embed
shot_2020_12_07_19_51

Similar thing also happens with mentions:
shot_2020_12_07_19_52

Is it possible to remove these embeds so that they don't take up space?

### PR DESCRIPTION
**Pull request by jonaharagon**
Fixes #641 

The other issue mentioned (matrix.to mention embeds) in #641 does not appear to be in this repo, ~~but rather it depends on https://github.com/matrix-discord/matrix-discord-parser/pull/11 being merged~~. Unsure what the fix is actually, but pretty sure it's somewhere in that dependency.

### CODE REVIEW

**Comment by MightyCreak** [comment]
Do you think it would be possible to fix #644 at the same time?

The idea would be to use the Discord endpoint to edit a message: https://discord.com/developers/docs/resources/webhook#edit-webhook-message

**Comment by shmerl** [comment]
An update on this one? I.e. can it be merged or something is blocking it?

**Review by Mailaender — APPROVED** [review]
I can confirm that this is the official way to avoid embeds: https://support.discord.com/hc/en-us/articles/206342858--How-do-I-disable-auto-embed-

**Review by auscompgeek — APPROVED** [review]
Definitely seems like a reasonable solution until someone comes along to implement webhook edits.

**Comment by AnonyPla** [comment]
Please merge this pull request! It's an annoying issue and the fix is really simple.

**Comment by AAGaming00** [comment]
> Do you think it would be possible to fix #644 at the same time?
> 
> The idea would be to use the Discord endpoint to edit a message: https://discord.com/developers/docs/resources/webhook#edit-webhook-message

check [my fork](https://github.com/aagaming00/matrix-appservice-discord) but note that it has issues with embeds that need to be fixed.

**Comment by MightyCreak** [comment]
@AAGaming00 could you do a PR or point us to the branch? where you implemented it? (PR would be better for review)

**Comment by AAGaming00** [comment]
@MightyCreak https://github.com/AAGaming00/matrix-appservice-discord/blob/develop/src/bot.ts#L473
Not making a pr due to the aforementioned issues which I don't have the time and knowledge to fix, but someone with knowledge of this project's structure probably can

**Comment by johannesrld** [comment]
any reason this was closed?

**Comment by shmerl** [comment]
Does this issue still persist?

**Comment by Mailaender** [comment]
Yes.

**Pull request closed without merging**
