### PR TITLE
Update better-sqlite3 to 6.0.1

### LINKED ISSUE #574: Not working on linux due to better-sqlite being broken on node lts 12
`npm install` fails to install dependencies due to this bug

https://github.com/JoshuaWise/better-sqlite3/issues/310

### PR DESCRIPTION
**Pull request by fanch317**
Fixes #574

### CODE REVIEW

**Comment by Sorunome** [comment]
Great, thank you for the PR!

**Comment by Sorunome** [comment]
Eeeeer can you please make this PR from `develop` and into `develop`?

**Comment by fanch317** [comment]
> 
> 
> Eeeeer can you please make this PR from `develop` and into `develop`?

Yes, i changed the PR for the develop branch.

**Comment by auscompgeek** [comment]
Looks like this needs another rebase.

**Comment by Sorunome** [comment]
Sorry, soru forgot to get back to this :S it was easier to manually just update it in the `develop` branch now - thanks a lot for the PR, though!

**Pull request closed without merging**
