### PR TITLE
Fix #437: Assume power level 50 for @room perm

### LINKED ISSUE #437: M->D at-room
assume a needed power level of 50 if `notifications.room` is not set in `m.room.power_levels`

### PR DESCRIPTION
**Pull request by Pneumaticat**
Rooms by default do not have notifications.room set in m.room.power_levels. If
they don't, assume @room requires default permissions (power level of 50).

edit: i apologize to at-room on github for mentioning them

### CODE REVIEW

**Comment by Sorunome** [comment]
> edit: i apologize to at-room on github for mentioning them

tbh, those called @everyone, @room and @here kinda asked for it xP


Anyhow, it looks great! Would you like to add a testcase for this, too? If not, soru can add it ^^

**Comment by Pneumaticat** [comment]
Sure! I will try to add one tonight.

**Comment by Pneumaticat** [comment]
Added a test and rearranged a few bits, not sure if it's the best approach. Feel free to suggest a different way.

**Comment by Sorunome** [comment]
looking good, except for that linting fails! https://travis-ci.org/Half-Shot/matrix-appservice-discord/jobs/524294827

you can check with `npm run lint` locally ^^

**Comment by Pneumaticat** [comment]
Whoops, should be fixed now. Thanks for the catch!

**Comment by Sorunome** [comment]
Looks awesome, thank you!

**Pull request merged**
