### PR TITLE
remove old config values

### PR DESCRIPTION
**Pull request by Sorunome**

### CODE REVIEW

**Comment by Half-Shot** [comment]
#454 already does this, and also removes the migration code.

**Comment by Sorunome** [comment]
@Half-Shot should we merge that one soon, then? what about metrics?

**Comment by Half-Shot** [comment]
Well, we still need these values for migrating 0.4 -> 0.5.

0.5.1 will only contain metrics stuff, but otherwise should be treated as 0.5

0.6 will contain the bot-sdk stuff hopefully, and will probably be called 1.0

**Comment by Half-Shot** [comment]
>#454 already does this, and also removes the migration code.

apparently this was a lie, merging.

**Pull request merged**
